---
title: "Retina Samples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```

```{r, libraries}

library(Seurat)
library(cowplot)
library(SCFunctionsV3)
library(dplyr)
library(tidyr)
library(stringr)
library(tidyverse)
library(DoubletFinder)
library(pheatmap)


### Functions
howManyCells <- function(sObj){dim(sObj)[2]}


### Functions
preDoublets <- function(seuratObj){  
    seuratObj <- NormalizeData(seuratObj)
    
    seuratObj <- ScaleData(seuratObj)
    seuratObj <- FindVariableFeatures(seuratObj, 
                                      x.low.cutoff = 0.0125, 
                                      y.cutoff = 0.25, 
                                      do.plot=FALSE)
    seuratObj <- RunPCA(seuratObj, pc.genes = seuratObj@var.genes, pcs.print = 0)
    
    # set.seed(1234)
    # seuratObj <- RunTSNE(seuratObj, dims.use = 1:10, verbose=TRUE)
    return(seuratObj)
}

findDoublets <- function(seuratObj){
    
    ### calculate expected number of doublets
    nExp_poi  <- round(0.15*nrow(seuratObj@meta.data))
    
    ### predict doublets
    seuratObj <- doubletFinder_v3(seuratObj, 
                                  PCs = 1:10, 
                                  pN = 0.25, 
                                  pK = 0.01, 
                                  nExp = nExp_poi, 
                                  reuse.pANN = FALSE, 
                                  sct=FALSE)
    
    
    seuratObj@meta.data <- seuratObj@meta.data %>% 
        rename_at(vars(starts_with("DF.classifications")), 
                  funs(str_replace(., ".*", "DF.classifications"))) %>%
        rename_at(vars(starts_with("pANN")), 
                  funs(str_replace(., ".*", "pANN")))
    
    return(seuratObj) 
    
}



sObj_Filtered <- readRDS("rObjects/sObj_Filtered.rds")

#samples <- list.files("cellranger_data") 
sampleInfo <- readRDS("rObjects/sampleInfo.rds")
sampleInfo <- sampleInfo %>% rename(sample = "Sample", stage = "Stage")

name_list <- function(sObj){
  sample_name <- sObj$orig.ident %>% levels()
  return(sample_name)
}
# 
names(sObj_Filtered) <- lapply(sObj_Filtered,
                               name_list) %>% unlist()

#re-order to the same as sampleInfo
sObj_Filtered <- sObj_Filtered[sampleInfo$sample]


```



```{r, cluster_cells, eval = FALSE}
clusterCells <- function(sObj){
  sObj <- ScaleData(object = sObj, features = rownames(sObj))
  sObj <- RunPCA(object = sObj)
  sObj <- FindNeighbors(object = sObj)
  sObj <- FindClusters(object = sObj, resolution = 1.0)
  sObj <- RunUMAP(object = sObj, dims = 1:20)
  return(sObj)
}

sObj_Filtered <- lapply(sObj_Filtered, clusterCells)
saveRDS(sObj_Filtered, "rObjects/sObj_Filtered.rds")

```


Each sample was clustered at a resolution of 1. The clusters generated are shown below.


```{r, plot_umaps, fig.height=15, fig.width=15}

for (i in 1:13){
  sObj_Filtered[[i]]$stage <- sampleInfo[i, "stage"]
  sObj_Filtered[[i]]$sample <- sampleInfo[i, "sample"]
  
}
names(sObj_Filtered) <- sampleInfo$sample


## sort samples samples
sampleInfo$stageNO <- sampleInfo$stage %>% gsub("Late\\..*", "", .) %>% gsub("[^0-9.]", "", .) %>% as.numeric()



##plot samples
plotUMAP <- function(sObj){
  p1 <- DimPlot(sObj, label = TRUE) + ggtitle(paste(sObj$sample, sObj$stage))
  return(p1)}
lapply(sObj_Filtered, plotUMAP)


```

Marker genes were identified in each cluster. 
                  
```{r, find_markers}
for (i in 1:13){
  
  markers <- FindAllMarkers(sObj_Filtered[[i]], 
                            only.pos = TRUE, 
                            ogfc.threshold = 0.5 )
  markers <- markers %>% arrange(cluster, desc(avg_log2FC))
  
  fName <- paste0("csvFiles/", "retina", sampleInfo$sample[i], "_", sampleInfo$stage[i], ".csv")
  write.csv(markers, fName)
  fName <- gsub("csvFiles", "rObjects", fName)
  saveRDS(markers, fName)
  
}



```

